name = "my name is {name} my age is {age}"

print(name.capitalize())
print(name.count("o"))
print(name.center(20, "-"))
print(name.endswith("d"))
print(name.expandtabs(tabsize=5))
print(name.find("a"))
# print(name[name.find("o"):9])
print(name.format(name='john', age=18))

print("3.14".isdecimal())
print("abc".isalpha())
print("1A".isdigit())
print(name.islower())
print(name.isupper())
print("3".isnumeric())
print(" ".isspace())
print("+".join(['1', '2', '3']))
print(name.ljust(50, "+"))
print(name.rjust(50, "+"))
print("JOHN".lower())
print("john".upper())
print(" hello  ".strip())
print(name.split(" "))
# print(name.replace("n", "N", 1))
print(name.swapcase())
print(name)
